services:
  db:
    # build: ./init_sql
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: riot
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: ./python
    restart: always
    working_dir: /app/
    tty: true
    volumes:
      - .:/app
    ports:
      - "8888:8888"

volumes:
  db_data:

# jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root